### ISSUE TITLE
Attachments?

### ISSUE THREAD

**Issue by neatcode** [emailjs/emailjs-smtp-client#27]
How do I send attachments?

**Comment by Axel186** [comment]
With emailjs-smtp-client you can send RFC messages.
To send an attachments you need to build message with attachment nodes.

With this one you can build RFC messages:
https://github.com/emailjs/emailjs-mime-builder

Take a look at attachment part: https://github.com/emailjs/emailjs-mime-builder#attachments

**Comment by neatcode** [comment]
Thank you
