### ISSUE TITLE
Instructions for browser usage are broken

### ISSUE THREAD

**Issue by Clonkex** [emailjs/emailjs-smtp-client#42]
I have no clue how I'm supposed to use this in the browser since the instructions are broken. It says
>Include files emailjs-smtp-client-response-parser.js and emailjs-smtp-client.js on the page.

but those files no longer exist in the repo. So... what do I do? There's no dist directory with a file to include. I tried including `client.js` but I just got `Uncaught SyntaxError: Unexpected token {`.

**Comment by felixhammerl** [comment]
The repo is under heavy construction and refactoring. Please use the latest released npm version, for which you'll find the instructions here: https://github.com/emailjs/emailjs-smtp-client/tree/13ef6398bc0abff5aa4bbe3050eb6905e302bb53

**Comment by tmikaeld** [comment]
The instructions doesn't seem to match the latest release and is it possible to compile this into a single file? I'm trying to use it on cloudflare workers where imports and files are not possible.
