### ISSUE TITLE
Why I receive Uncaught (in promise) TypeError: this.socket.send is not a function 

### ISSUE THREAD

**Issue by wwwork** [emailjs/emailjs-smtp-client#50]
I try to send gmail via emailjs-smtp-client at google chrome, opera and firefox. It has emailjs-tcp-socket in depencencies list.

I've tried to set timeouts at emailjs-smtp-client/src/client.js
```

const TIMEOUT_SOCKET_LOWER_BOUND = 100000
const TIMEOUT_SOCKET_MULTIPLIER = 0.01
```
It did not help, same result.

Init connection at vue template:
```

import SmtpClient from 'emailjs-smtp-client';
let client = {};
let options = {};
let alreadySending = false;
options = {
    auth: {
        user: mail.mail,
        pass: mail.pass,
        ca: true,
        ignoreTLS: false,
        requireTLS: true,
    },
};
client = new SmtpClient(mail.host, 587, options);
client.onidle = () => {
    console.log('Connection has been established');
    if (alreadySending) {
        return;
    }
    alreadySending = true;
    client.useEnvelope({
        from: mail.mail,
        to: mail.mail,
    });
};
client.onready = () => {
    client.send('Subject: test\r\n');
    client.send('\r\n');
    client.send('Message body');
    client.end();
};
client.onerror = (err) => {
    console.log(err);
};
client.ondone = (success) => {
    if (success) {
        // show succes send message
        console.log('The message was transmitted successfully');
    }
};
client.quit();
```
`command > telnet smtp.gmail.com 587`

, runs and connects fine.

In FireBug, -> network tab -> WS connection is empty.

I receive the Error in console.

> 
Uncaught (in promise) TypeError: this.socket.send is not a function at SmtpClient._send (client.js?00c3:486) at SmtpClient._sendCommand (client.js?00c3:480) at SmtpClient.quit (client.js?00c3:177) at eval (VM5894 761:276) at _send @ client.js?00c3:486 _sendCommand @ client.js?00c3:480 quit @ client.js?00c3:177 fn._withTask.fn._withTask @ vue.esm.js?65d7:1826 VM5894 761:269 Error: Socket timed out! at SmtpClient._onTimeout (client.js?00c3:419)

**Comment by rongdilin** [comment]
same error here

**Comment by victorious85** [comment]
same error here
